# /.github/workflows/daily.yml
# based on https://github.com/sw-yx/gh-action-data-scraping
on:
  schedule:
    - cron:  '0 8 * * *' # every day at 8am
name: Pull Data and Build
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Log Python location
      run: which python
    - name: Scrape
      run: |
        curl -o data/epa-superfunds-raw.json --no-progress-meter "https://www.epa.gov/sites/production/files/buckeye_symlinks/semsjson/Human_Exposure_Site_List.json?_=$(date +%s)"
    - name: Pretty Print the JSON
      run: |
        cat data/epa-superfunds-raw.json | python -m json.tool > data/epa-superfunds.json
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
